HOST_DB1 = "notas-aws.cvjcytn72njy.us-east-1.rds.amazonaws.com"
HOST_DB2 = "notasazure.mysql.database.azure.com"
USER_DB1 = "notasroot"
USER_DB2 = "notasroot@notasazure"
PASSWORD_DB = "password01*"
DB1_NAME="clases"
DB2_NAME="clases2"

QUERY_CREATE_DB1 = "CREATE DATABASE IF NOT EXISTS clases"
QUERY_CREATE_DB2 = "CREATE DATABASE IF NOT EXISTS clases2"